Repository PenPow/SignalBot, pull requests merged in 2021-07, with the labels that each got.

#3 refactor(ActionManagers): Refactor Events and Fix the Bugs
  .pnp.js
  .yarn/cache/fs-npm-0.0.1-security-5060b47e87-d23d3c0dd4.zip
  package.json
  src/events/debug.js
  src/events/error.js
  src/events/guildCreate.js
  src/events/guildMemberAdd.js
  src/events/interaction.js
  src/events/interactionCreate.js
  src/events/message.js
  src/events/messageCreate.js
  src/events/messageUpdate.js
  src/events/ratelimit.js
  src/events/ready.js
  src/events/warn.js
  src/managers/ActionManager.js
  src/structures/Client.js
  src/utils/utils.js
  yarn.lock
Labels: bug

#9 chore(docs): Improve Documentation for Issues, Pull Requests, and Contributions
  .github/CONTRIBUTING.MD
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ESLint.yml
Labels: documentation, enhancement

#27 Update CONTRIBUTING.MD
  .github/CONTRIBUTING.MD
Labels: documentation

#31 fix(semver): Fixes Documentation with Node Version
  app.js
  package.json
Labels: documentation

#32 docs(License): Move to MIT License
  LICENSE
  README.md
Labels: documentation

#33 refactor(intents)
  app.js
Labels: p: high, refactor

#34 Update Dependabot.yml
  .github/workflows/Dependabot.yml
Labels: dependencies, enhancement

#36 refactor(Embeds): Signal Embeds
  package.json
  src/commands/fun/8ball.js
  src/commands/fun/bird.js
  src/commands/fun/cat.js
  src/commands/fun/catfact.js
  src/commands/fun/coinflip.js
  src/commands/fun/covid.js
  src/commands/fun/dog.js
  src/commands/fun/dogfact.js
  src/commands/fun/duck.js
  src/commands/fun/emojify.js
  src/commands/fun/fox.js
  src/commands/fun/meme.js
  src/commands/fun/roll.js
  src/commands/fun/rps.js
  src/commands/fun/shibe.js
  src/commands/fun/youtube.js
  src/commands/info/avatar.js
  src/commands/info/botinfo.js
  src/commands/info/channelinfo.js
  src/commands/info/help.js
  src/commands/info/members.js
  src/commands/info/permissions.js
  src/commands/info/ping.js
  src/commands/info/prefix.js
  src/commands/info/roleinfo.js
  src/commands/info/servericon.js
  src/commands/info/serverinfo.js
  src/commands/info/stats.js
  src/commands/info/userinfo.js
  src/commands/info/weather.js
  src/commands/misc/bugreport.js
  src/commands/misc/feedback.js
  src/commands/misc/nickname.js
  src/commands/mod/ban.js
  src/commands/mod/case.js
  src/commands/mod/kick.js
  src/commands/mod/mute.js
  src/commands/mod/reason.js
  src/commands/mod/softban.js
  src/commands/mod/unban.js
  src/commands/mod/unmute.js
  src/commands/owner/eval.js
  src/commands/owner/leaveguild.js
  src/commands/owner/reload.js
  src/commands/owner/servers.js
  src/structures/Command.js
  src/structures/SignalEmbed.js
Labels: p: medium, refactor, t: other

#40 refactor(flags): Use flags instead of strings for intents + permissions
  app.js
  src/commands/fun/8ball.js
  src/commands/music/volume.js
Labels: p: high, refactor

#41 feat(tags): Custom Tags System
  src/commands/music/play.js
  src/commands/tags/tag.js
  src/events/messageCreate.js
  src/structures/Client.js
Labels: enhancement
